'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {request} from '../../lib/api';
import Icon from '../../components/Icon';
import Modal from '../../components/Modal';
import {ReadingArt,LibraryBanner} from '../../components/LibraryArt';
const empty={title:'',author:'',category:'',status:'Available'},pageSize=8;
export default function Dashboard(){
 const router=useRouter();
 const [books,setBooks]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[sort,setSort]=useState({key:'',direction:1});
 const [modal,setModal]=useState(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[modalError,setModalError]=useState(''),[drawer,setDrawer]=useState(false),[menu,setMenu]=useState(false),[user,setUser]=useState(null),[notice,setNotice]=useState(false);
 const logout=useCallback(()=>{localStorage.removeItem('token');localStorage.removeItem('user');router.replace('/login')},[router]);
 const load=useCallback(async()=>{try{setError('');setBooks(await request('/crud/books'))}catch(e){if(e.status===401)logout();else setError(e.message)}finally{setLoading(false)}},[logout]);
 useEffect(()=>{if(!localStorage.getItem('token')){router.replace('/login');return}try{setUser(JSON.parse(localStorage.getItem('user')||'null'))}catch{}load()},[load,router]);
 useEffect(()=>{setPage(1)},[query,category,status]);
 const categories=useMemo(()=>[...new Set(books.map(b=>b.category))].sort(),[books]);
 const filtered=useMemo(()=>{const result=books.filter(b=>(!category||b.category===category)&&(!status||b.status===status)&&[b.title,b.author,b.category].some(v=>v.toLowerCase().includes(query.toLowerCase())));return sort.key?result.sort((a,b)=>a[sort.key].localeCompare(b[sort.key])*sort.direction):result},[books,query,category,status,sort]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,pages),rows=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize),available=books.filter(b=>b.status==='Available').length,borrowed=books.filter(b=>b.status==='Borrowed').length;
 function open(book){setForm(book?{title:book.title,author:book.author,category:book.category,status:book.status}:{...empty});setModal({kind:'book',book});setModalError('')}
 async function save(e){e.preventDefault();if(busy)return;const data={...form,title:form.title.trim(),author:form.author.trim(),category:form.category.trim()};if(!data.title||!data.author||!data.category){setModalError('Please complete all required fields.');return}setBusy(true);setModalError('');try{await request(modal.book?`/crud/books/${modal.book.id}`:'/crud/books',{method:modal.book?'PUT':'POST',body:JSON.stringify(data)});setModal(null);await load()}catch(e){setModalError(e.message)}finally{setBusy(false)}}
 async function remove(){if(busy)return;setBusy(true);setModalError('');try{await request(`/crud/books/${modal.book.id}`,{method:'DELETE'});setModal(null);await load()}catch(e){setModalError(e.message)}finally{setBusy(false)}}
 function reset(){setQuery('');setCategory('');setStatus('');setPage(1);setSort({key:'',direction:1})}
 function nav(item){setDrawer(false);if(item==='Dashboard')window.scrollTo({top:0,behavior:'smooth'});if(item==='Books')document.getElementById('books').scrollIntoView({behavior:'smooth'});if(item==='Categories')document.getElementById('category-filter').focus();if(item==='Profile')setModal({kind:'profile'})}
 return <div className="app-shell">{drawer&&<button className="drawer-backdrop" aria-label="Dismiss navigation" onClick={()=>setDrawer(false)}/>}
 <aside className={`sidebar ${drawer?'is-open':''}`}><button className="icon-button sidebar-close" aria-label="Close navigation" onClick={()=>setDrawer(false)}><Icon name="close"/></button><a className="brand" href="/dashboard"><span className="brand-icon"><Icon size={43}/></span><span><strong>Library</strong><small>Management System</small></span></a><nav aria-label="Main navigation">{[['Dashboard','home'],['Books','book'],['Categories','grid'],['Profile','user']].map(([label,icon])=><button key={label} className={`nav-item ${label==='Dashboard'?'active':''}`} onClick={()=>nav(label)}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="reading-card"><ReadingArt/><p>Good Reading<br/>Builds a<br/>Brighter Future</p><div className="reading-line"/></div></aside>
 <div className="main-shell"><header className="header"><button className="icon-button mobile-toggle" aria-label="Open navigation" onClick={()=>setDrawer(true)}><Icon name="menu"/></button><label className="search-input header-search"><Icon name="search"/><input aria-label="Search library" placeholder="Search books, author, category..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="header-right"><div className="notification-wrap"><button className="bell-button" aria-label="Notifications" onClick={()=>setNotice(!notice)}><Icon name="bell" size={25}/></button>{notice&&<div className="header-popover">You’re all caught up.</div>}</div><div className="user-wrap"><button className="user-button" aria-label="Admin account menu" onClick={()=>setMenu(!menu)} aria-expanded={menu}><span className="avatar"><Icon name="user" size={25}/></span><span className="user-copy"><strong>Admin</strong><small>Administrator</small></span><Icon name="down" size={18}/></button>{menu&&<div className="header-popover user-menu"><span>{user?.email}</span><button onClick={logout}>Logout</button></div>}</div></div></header>
 <main className="dashboard"><section className="hero"><LibraryBanner/><div className="hero-copy"><h1>Library <span>Dashboard</span></h1><p>Manage books, categories and library resources</p></div></section>
 <section className="stats" aria-label="Library statistics">{[{title:'Total Books',value:books.length,icon:'book',color:'blue',note:'Books in your library'},{title:'Available',value:available,icon:'check',color:'green',note:`${books.length?(available/books.length*100).toFixed(1):'0'}% of total`},{title:'Borrowed',value:borrowed,icon:'book',color:'red',note:`${books.length?(borrowed/books.length*100).toFixed(1):'0'}% of total`},{title:'Categories',value:categories.length,icon:'layers',color:'purple',note:'Across your collection'}].map(s=><div className={`stat-card ${s.color}`} key={s.title}><span className="stat-icon"><Icon name={s.icon} size={33}/></span><div className="stat-copy"><span>{s.title}</span><strong>{loading?'—':s.value}</strong><small>{s.note}</small></div>{s.color!=='blue'&&<svg className="sparkline" viewBox="0 0 70 45" aria-hidden="true"><path d="M2 27Q12 3 25 15T47 13T68 12" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="M2 27Q12 3 25 15T47 13T68 12V45H2Z" fill="currentColor" opacity=".05"/></svg>}</div>)}</section>
 <section className="books-card" id="books"><div className="books-heading"><div className="books-heading-copy"><span className="section-icon"><Icon size={33}/></span><div><h2>Books</h2><p>Add, edit or remove books from the library</p></div></div><button className="btn primary" onClick={()=>open(null)}><Icon name="plus"/>Add Book</button></div><div className="filters"><label className="search-input"><Icon name="search" size={20}/><input aria-label="Search books" placeholder="Search by title, author or category..." value={query} onChange={e=>setQuery(e.target.value)}/></label><select id="category-filter" aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All Categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option><option>Available</option><option>Borrowed</option></select><button className="btn reset" onClick={reset}><Icon name="reset" size={20}/>Reset</button></div>
 {error&&<div className="error" role="alert">{error} <button onClick={load}>Retry</button></div>}
 <div className="table-wrap"><table><thead><tr><th className="number-col">#</th>{[['title','Title'],['author','Author'],['category','Category'],['status','Status']].map(([key,label])=><th key={key} aria-sort={sort.key===key?(sort.direction===1?'ascending':'descending'):'none'}><button className="sort-button" onClick={()=>setSort({key,direction:sort.key===key?-sort.direction:1})}>{label}<span>↕</span></button></th>)}<th>Actions</th></tr></thead><tbody>{rows.map((b,i)=><tr key={b.id}><td>{(currentPage-1)*pageSize+i+1}</td><td><div className="book-title"><span className={`book-cover cover-${i%3}`} aria-hidden="true"><span>{b.title}</span><i/><small>{b.author}</small></span><strong>{b.title}</strong></div></td><td>{b.author}</td><td><span className={`category-badge ${categories.indexOf(b.category)%2?'purple':'blue'}`}>{b.category}</span></td><td><span className={`status-badge ${b.status==='Available'?'available':'borrowed'}`}><i/>{b.status}</span></td><td><div className="actions"><button className="icon-button" title="Edit" aria-label={`Edit ${b.title}`} onClick={()=>open(b)}><Icon name="edit" size={20}/></button><button className="icon-button delete-button" title="Delete" aria-label={`Delete ${b.title}`} onClick={()=>{setModal({kind:'delete',book:b});setModalError('')}}><Icon name="trash" size={20}/></button></div></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="empty-state">{loading?'Loading your library…':error?'Books could not be loaded.':'No books found. Try changing your filters or add a book.'}</td></tr>}</tbody></table></div><footer className="table-footer"><span>Showing {filtered.length?(currentPage-1)*pageSize+1:0} - {Math.min(currentPage*pageSize,filtered.length)} of {filtered.length} books</span><div className="pagination"><button aria-label="Previous page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><Icon name="left" size={18}/></button><span aria-current="page">{currentPage}</span><button aria-label="Next page" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><Icon name="right" size={18}/></button></div></footer></section>
 </main></div>
 {modal&&<Modal title={modal.kind==='delete'?'Delete Book?':modal.kind==='profile'?'Your profile':modal.book?'Edit Book':'Add Book'} onClose={()=>setModal(null)} busy={busy}>{modal.kind==='book'?<form onSubmit={save}><p className="modal-subtitle">{modal.book?'Update the details of your book.':'Add a new book to your library.'}</p>{['title','author','category'].map(key=><label className="field" key={key}>{key[0].toUpperCase()+key.slice(1)}<input autoFocus={key==='title'} required maxLength={200} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} list={key==='category'?'categories':undefined}/></label>)}<datalist id="categories">{categories.map(c=><option key={c} value={c}/>)}</datalist><label className="field">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Available</option><option>Borrowed</option></select></label>{modalError&&<p className="error" role="alert">{modalError}</p>}<div className="modal-actions"><button type="button" className="btn secondary" disabled={busy} onClick={()=>setModal(null)}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving…':modal.book?'Update Book':'Add Book'}</button></div></form>:modal.kind==='delete'?<><p className="delete-copy">Are you sure you want to delete <strong>“{modal.book.title}”</strong>?</p><p className="muted">This action cannot be undone.</p>{modalError&&<p className="error" role="alert">{modalError}</p>}<div className="modal-actions"><button className="btn secondary" disabled={busy} onClick={()=>setModal(null)}>Cancel</button><button className="btn danger" disabled={busy} onClick={remove}>{busy?'Deleting…':'Delete'}</button></div></>:<><p className="profile-name">{user?.name||'Admin'}</p><p className="muted">{user?.email}</p><div className="modal-actions"><button className="btn primary" onClick={logout}>Logout</button></div></>}</Modal>}
 </div>
}


